[env:head]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
build_flags =
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -Isrc/config
    -Isrc/command
    -Isrc/servo
lib_deps =
    links2004/WebSockets@2.7.3
    ESP32Servo

[env:native]
platform = native
test_build_src = false
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Itest/stubs
    -Itest
    -Isrc/config
    -Isrc/command
    -Isrc/servo
lib_deps =
    https://github.com/meekrosoft/fff.git
