[env:wemos_d1_uno32]
platform = espressif32
board = wemos_d1_uno32
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Isrc/config
    -Isrc/motor
    -Isrc/motor/constants
    -Isrc/motor/driver
    -Isrc/drivetrain
    -Isrc/drivetrain/controller
    -Isrc/imu
    -Isrc/input
    -Isrc/control
    -Isrc/util
build_unflags = -std=gnu++11

[env:native]
platform = native
test_build_src = false
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Itest/stubs
    -Isrc/config
    -Isrc/motor
    -Isrc/motor/constants
    -Isrc/motor/driver
    -Isrc/drivetrain
    -Isrc/drivetrain/controller
    -Isrc/imu
    -Isrc/input
    -Isrc/control
    -Isrc/util
    -DBB8_DEBUG
